# Generated by Django 4.2.4 on 2023-08-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userdoctor_position_alter_userdoctor_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdoctor',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='core.position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdoctor',
            name='prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='core.professions'),
            preserve_default=False,
        ),
    ]
